title: Data Products Group
author: Data Products Group, Ocean Sciences Division at the Institute of Ocean Sciences in Sidney, B.C.

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  For questions or comments please contact us at: DFO.PAC.SCI.IOSData-DonneesISO.SCI.PAC.MPO@dfo-mpo.gc.ca

theme: minima #jekyll-theme-slate

plugins:
  - jekyll-feed
  - jekyll-seo-tag

#show_downloads: false

github_username: ios-osd-dpg

minima:
  date_format: "%Y-%m-%d"
  social_links:
     - { platform: github,         user_url: "https://github.com/ios-osd-dpg" }

# Minima: custom header links
header_pages:
  - README.md
  - pages/published_datasets.md

include:
  - pages

exclude: 
  - .gitignore
